# Generated by Django 5.0.3 on 2025-01-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('classification', models.CharField(max_length=100)),
                ('evidence', models.TextField()),
            ],
        ),
    ]
