# Generated by Django 5.0.3 on 2025-01-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringdata',
            name='evidence',
        ),
        migrations.AddField(
            model_name='monitoringdata',
            name='evidence_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
