# Generated by Django 5.0.3 on 2025-01-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_monitoringdata_evidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoringdata',
            old_name='classification',
            new_name='object_class',
        ),
    ]
